#!/usr/bin/env bash
# configure server to listen on port 80

# remove the defualt Nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure Nginix to listen on port 80 for all active IPv4 IPs
In -S /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
